### ISSUE TITLE
Issue with forward method of Sigmoid class.

### ISSUE THREAD

**Issue by admin-trokictech** [DrBigMau/LSTM-from-Scratch-in-Python#1]
Hi there! 

I think your repository is wonderful! 

I also think the youtube videos are an absolute gem! I don't think I've seen any other instructional content on the web which is more clear and helpful than yours. Well done!

However, I do think there is a tiny issue in the forward and backward methods of your Sigmoid class. As you can see below, you've defined the following methods

```
class Sigmoid:
        
    def forward(self, M):
        
        sigm        = np.clip(1/(1 + np.exp(-M)), 1e-7, 1 - 1e-7)
        self.output = sigm
        self.inputs = sigm #needed for back prop

    def backward(self, dvalues):
        
        sigm         = self.inputs
        deriv        = np.multiply(sigm, (1 - sigm))
        self.dinputs = np.multiply(deriv, dvalues)
```
        
       
However, in the forward method, I believe, `self.inputs = sigm` is **not** correct and it should read `self.inputs = M` as `M` is the input and `sigm` is the output. 

Furthermore in the backward method, `sigm = self.inputs` is **not** correct and it should read `sigm = self.outputs`.

**Comment by DrBigMau** [comment]
Hi Back : )

Thank you very much for your email and thanks a lot for watching my videos.
I am glad that you like them.
I have checked the bug.

self.inputs = sigm is indeed misleading, because it should be
self.inputs = M as you pointed out and as it would follow the notation in
the code.

It turned out, that, fortunately, the bug is without consequences because

self.inputs = sigm

is assigned correctly for backprop

    def backward(self, dvalues):

        sigm           = self.inputs
        deriv           = np.multiply(sigm, (1 - sigm))
        self.dinputs = np.multiply(deriv, dvalues)

and the derivative is calculated correctly.

Nevertheless, I have corrected the corresponding lines.

Bests,

Mau
